# Generated by Django 4.2.3 on 2023-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('s_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(choices=[], max_length=10)),
                ('product_id', models.PositiveSmallIntegerField(unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('date_of_purchase', models.DateField(auto_created=True, auto_now_add=True)),
                ('s_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=12, unique=True)),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('return_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=10)),
                ('seller_id', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('s_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=10)),
                ('brand', models.CharField(help_text='Classmate, Levis, etc.', max_length=10)),
                ('category', models.CharField(help_text='soap, oil, etc.', max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product_id', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('s_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=32)),
                ('seller_email', models.EmailField(max_length=32)),
                ('seller_phone', models.SmallIntegerField()),
                ('seller_address', models.TextField(max_length=300)),
                ('seller_id', models.PositiveSmallIntegerField(default=681330, unique=True)),
            ],
        ),
    ]
