# Generated by Django 4.2.3 on 2023-12-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.PositiveSmallIntegerField(default=344250, unique=True),
        ),
    ]
