# Generated by Django 4.2.3 on 2023-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.CharField(choices=[('---', '---')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.PositiveSmallIntegerField(default=646280, unique=True),
        ),
    ]
